Hot fixes to unit tests
dockstore/data-object-service-plugin pull request #5
Opened 2018-09-27 20:55 UTC by rjbautis

* Cleans up test cases
* Removes and/or replaces broken DOS URIs in certain unit test cases

2018-09-28 14:05 UTC, denis-yuen commented
Looks like certain build dependencies are missing, @coverbeck vaguely recall an issue having to do with this. How did this work before?

2018-09-28 15:53 UTC, coverbeck commented
@denis-yuen Not sure, will investigate. Also, I think this PR is not quite ready and should not yet have been assigned reviewers; sorry for the confusion.

2018-10-01 23:37 UTC, coverbeck requested changes
A lot of nit-picky stuff, but this is also (hopefully) a learning/teaching experience.

Also, as we discussed, I would not call this "Hot fixes".

Finally, I think your commit message should both reference the GitHub issue, and it should mention that you are removing dependencies on external servers for the tests to pass.

2018-10-01 23:37 UTC, coverbeck commented on src/main/java/io/dockstore/provision/DOSPlugin.java
>              if (uri.isPresent() && schemesHandled().contains(uri.get().getLeft())) {
This is really a comment for line 55, but GitHub doesn't let a user comment on lines that weren't changed...

This is really minor, but I would have a static final for `return new HashSet..`. Otherwise you're creating new objects every time this method is invoked.

In this particular case it won't effectively matter, as the method is only called twice and 2 objects will have no noticeable impact on performance, but just mentioning as a learning experience for future programming where a similar method might get invoked tens of thousands of times.

2018-10-01 23:37 UTC, coverbeck commented on src/main/java/io/dockstore/provision/DOSPluginUtil.java
> +            return Optional.of(new JSONObject(content));
I think `new JSONObject(content)` will fail if content is null. Are you relying on the catch to handle that case? I think it's clearer if you do an explicit null check. One way could be:

```
if (content != null) {
   return Optional.of(new JSONObject(content))
}
```

Or you could do something fancier with a map

2018-10-01 23:37 UTC, coverbeck commented on src/main/java/io/dockstore/provision/DOSPluginUtil.java
> +        Optional<InputStream> JSONResponse;
Java variable names should not start with a capital, unless they are static final, in which case they are all caps.

2018-10-01 23:37 UTC, coverbeck commented on src/main/java/io/dockstore/provision/DOSPluginUtil.java
> +        Optional<InputStream> JSONResponse;
Also, I would move both this and the preceding declaration inside the try block and initialize/declare them together, e.g.,

```
final JSONResponse jsonResponse = downloadJSON(immutableTriple);
```

2018-10-01 23:37 UTC, coverbeck commented on src/main/java/io/dockstore/provision/DOSPluginUtil.java
> +    private HttpURLConnection conn;
It would be better if this were a method variable rather than a field, IMHO.

I guess it's tricky to close the connection though.

2018-10-02 20:23 UTC, rjbautis commented on src/main/java/io/dockstore/provision/DOSPlugin.java
>              if (uri.isPresent() && schemesHandled().contains(uri.get().getLeft())) {
Sounds good, I will include the change.

2018-10-03 22:41 UTC, coverbeck approved these changes
Looks good!

Please wait for approval from @garyluu and @agduncan94 before merging...

2018-10-04 20:22 UTC, agduncan94 approved these changes

2018-10-05 14:06 UTC, garyluu approved these changes

2018-10-05 20:15 UTC, merged

2018-10-05 20:20 UTC, rjbautis commented
* Updates unit tests to remove dependency on live server using proper mocks
* Refactors method names & signatures as well as variables in src code